#!/bin/bash
VOLUME="$PWD"

docker run -v "$PWD:/home" \
	-it --rm isp /sbin/my_init --quiet -- \
	"/usr/bin/mpicc" "-L/usr/local/lib" "-I/usr/local/include/isp" \
	-Wl,-rpath=/usr/local/lib -include isp.h $* -lisp_prof -lmpi_cxx

